<?xml version="1.0"?>
<robot name="tankpi" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- T265 Link -->
  <xacro:arg name="t265_xyz"     default="$(optenv T265_XYZ .110 0 .077)"/>
  <xacro:arg name="t265_rpy"     default="$(optenv T265_RPY 0 0 0)"/>
  <xacro:arg name="t265_parent"  default="$(optenv T265_PARENT base_link)"/>

  <!-- D435 Link -->
  <xacro:arg name="d534_xyz"     default="$(optenv D435_XYZ .030 0 .085)" />
  <xacro:arg name="d534_rpy"     default="$(optenv D435_RPY 0 0 0)" />
  <xacro:arg name="d534_parent"  default="$(optenv D435_PARENT t265_link)" />

  <!-- Base color -->
  <xacro:arg name="base_color"   default="$(optenv BASE_COLOR 33, 113, 213, 0.8)" />

  <xacro:property name="M_PI" value="3.14159"/>

  <!-- Base Size (Measured in inches and converted) -->
  <xacro:property name="base_x_size" value="0.308" />
  <xacro:property name="base_y_size" value="0.229" />
  <xacro:property name="base_z_size" value="0.200" />

  <!-- Track Mounting Positions -->
  <!-- Vertical offset is the height above/below the bottom plate -->
  <!-- Horizontal offset is the distance behind the center of the -->
  <!-- Bottom plate. Both are measured to center of the axle -->
  <xacro:property name="track_vertical_offset" value="0.005" />
  <xacro:property name="track_horizontal_offset" value="0.120" />

  <!-- Track Properties -->
  <xacro:property name="track_length" value="0.308" />
  <xacro:property name="track_width" value="0.030" />
  <xacro:property name="track_radius" value="0.035" />

  <!-- Base link is the center of the robot's bottom plate -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
      <material name="blue">
        <color rgba="${base_color}"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
  </link>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${track_vertical_offset - track_radius}" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!--
      T265 Link
  -->
  <link name="t265_link" />
  <joint name="t265_joint" type="fixed">
    <origin xyz="$(arg t265_xyz)" rpy="$(arg t265_rpy)" />
    <parent link="$(arg t265_parent)" />
    <child link="t265_link" />
  </joint>

  <!--
      D435 Link
  -->
  <link name="d435_link" />
  <joint name="d435_joint" type="fixed">
    <origin xyz="$(arg d435_xyz)" rpy="$(arg d435_rpy)" />
    <parent link="$(arg d435_parent)" />
    <child link="d435_link" />
  </joint>
</robot>
